// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwwzfmkapdmqbfyuvcgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3d3pmbWthcGRtcWJmeXV2Y2dsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNDA1NzgsImV4cCI6MjA2MzcxNjU3OH0.ZtveOjOcN3CO5Db4RXeMdhEp8OimNHmkUFsdXOyc0fk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);